### PR TITLE
Fixes several issues with the port

### PR DESCRIPTION
**Pull request by natesway**
Hey! Just wanted to say before hand, nice job on the project so far! I played through it, and there were some issues that were prevalent in the code, and in the mod itself. I fixed some issues with the mod that I'll list some things I fixed

- Stagnant GF not doing the specific animations meant for the song
- Fixed some compiling issues
- Stagnant now has the correct speed changes
- Markov is semi-complete.

Just wanted to contribute to this port. I'll continue to add more fixes and submit them if you need so. Thanks! - shatterstar9652

### CODE REVIEW

**Comment by DM-kun** [comment]
Oh damn, thanks a bunch! Any help is welcome and I'm glad you're interested in this :)
I'll have to update a few things again as the new updates had dropped a few days ago, but this'll really help!

**Comment by natesway** [comment]
No problem! I've been following this project for a while now (since august or so), so it's nice to contribute. I can help with some of the new things if needed, as it'll be cool to combine both of the mods together.

**Comment by natesway** [comment]
Hey! Just re-compiled the port after a little while, I see most of home's events aren't completed. Any luck on figuring them out? (Home just renders a black screen).

**Comment by DM-kun** [comment]
honestly, i just haven't worked on this for a long while since i've been busy with some other things
might work on this again when i have the time for it

**Comment by natesway** [comment]
Alright. I'm going to attempt to fix home in the time being. Any help would be appreciated.

**Comment by natesway** [comment]
Hey! Just like to add that I should be able to do a pull request soon to fix home, I just want to ask, is there any reason why Natsuki’s eye animation won’t work at all?

**Comment by natesway** [comment]
Managed to fix the issue. Currently just trying to fix an issue with girlfriends home sprite.

**Pull request merged**
